## Each new term in the Fibonacci sequence is generated by adding the previous two terms.
## By starting with 1 and 2, the first 10 terms will be:
## 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
## By considering the terms in the Fibonacci sequence whose values do not exceed
## four million, find the sum of the even-valued terms.

## check original statement
function fib(n)
    if n == 1
        return(1)
    end
    if n == 2
        return(2)
    end
    f1 = fib(n - 1)
    f2 = fib(n - 2)
    return(f1 + f2)
end
fib(10)

## instead, store as an array and add to it
using DataFrames
f = DataFrame(n = 1, fib = fib(1))
push!(f, (2, 2))
n = 3
while f.fib[end] + f.fib[end-1] < 4e6
    global n
    push!(f, (n, f.fib[n-1] + f.fib[n-2]))
    n += 1
end
sum([x for x in f.fib if x % 2 == 0])
